In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('survey_results_public.csv')
df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

Filter data hanya dari negara India saja

In [3]:
filt= df['Country']=='India'
df[filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
57,58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,...,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
62,63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
147,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64391,54757,NaN,Yes,NaN,18,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,A lot less welcome now than last year,NaN,5,Less than 1 year
64398,55407,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64439,62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
64442,62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64452,64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Bisa juga seperti ini

In [4]:
df[df['Country']=='India'].head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
57,58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,...,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
62,63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
147,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3

Filter data hanya India **atau** Germany

In [5]:
filt= (df['Country']=='India') | (df['Country']=='Germany')
df[filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
5,6,I am a developer by profession,No,NaN,14,NaN,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
22,23,I am a developer by profession,Yes,27.0,14,NaN,NaN,NaN,Germany,European Euro,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Somewhat less welcome now than last year,40.0,8,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64398,55407,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64402,56263,NaN,Yes,NaN,14,NaN,NaN,NaN,Germany,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Angular;jQuery;Ruby on Rails,Just as welcome now as I felt last year,NaN,7,NaN
64439,62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
64442,62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64452,64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Filter data orang bernegara India **dan** berumur di atas 20

In [6]:
filt= (df['Country']=='India') & (df['Age']>20)
df[filt]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
62,63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
147,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3
225,227,I am a developer by profession,Yes,24.0,19,Yearly,840000.0,11728.0,India,Indian rupee,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Gatsby,Flask;Spring,Somewhat more welcome now than last year,45.0,5,2
232,234,I am a developer by profession,Yes,22.0,16,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask,Angular;Angular.js;Django;Flask;jQuery,Just as welcome now as I felt last year,NaN,4,NaN
272,274,I am a developer by profession,Yes,26.0,17,NaN,NaN,NaN,India,Indian rupee,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",Angular;Express,Angular;Express,NaN,40.0,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62211,63515,I am a student who is learning to code,Yes,22.0,17,NaN,NaN,NaN,India,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express,ASP.NET;ASP.NET Core;Express,Just as welcome now as I felt last year,NaN,5,NaN
62522,63850,I am a student who is learning to code,Yes,21.0,21,NaN,NaN,NaN,India,NaN,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",Angular.js;ASP.NET;Django;React.js,jQuery,NaN,NaN,2,NaN
63546,64969,I am a developer by profession,Yes,21.0,15,NaN,NaN,NaN,India,NaN,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",Angular;Django;Flask;React.js,Django;Flask,NaN,NaN,4,NaN
63716,65149,I am a student who is learning to code,Yes,21.0,18,NaN,NaN,NaN,India,NaN,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",Ruby on Rails,Ruby on Rails,A lot more welcome now than last year,NaN,3,NaN
64278,31248,NaN,Yes,35.0,16,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular.js;React.js;Spring,Angular.js;Spring,Just as welcome now as I felt last year,NaN,7,3